[package]
name = "simple-database-in-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
bytes = "1.2.1"
serde = { version = "1.0.14", features = ["derive"] }
